### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by aronne0pefkkcpoekk** [DurtyFree/durty-cloth-tool#173] opened 2024-02-12 22:49 UTC
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at (Object )
   at uhEU3TfBn6wUbNUvIFQ9.XGEf4oUTHpC(Object , uhEU3TfBn6wUbNUvIFQ9 )
   at NENn0LPd4rMOW2opoyE.kjl4egPNmgwenJbWMw9.HHhPIquiJ1(DateTime  , String  )
   at NENn0LPd4rMOW2opoyE.kjl4egPNmgwenJbWMw9.VflPnjcBqB(String  )
   at HdINi4NRCadndIgU1JG.r8mMtFN5moqtdWZUdGl.uQqodV0fHWxYZYcKF8Dx(Object , Object )
   at HdINi4NRCadndIgU1JG.r8mMtFN5moqtdWZUdGl.uE6NmSKmmS(String  )
   at g5YZCKyLoRBfWbfeAZr.cva0XDymK79KvLRb2HV.iSAljuym2iUldhf4YsEM(Object , Object )
   at g5YZCKyLoRBfWbfeAZr.cva0XDymK79KvLRb2HV.E6ByxaiMVk(Exception  , String  )
   at g5YZCKyLoRBfWbfeAZr.cva0XDymK79KvLRb2HV.HYxy2OcviQ(Object  , DispatcherUnhandledExceptionEventArgs  )
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at tBb27pf4JFHIIstxsxKx.XGEf4oUTHpC(Object , tBb27pf4JFHIIstxsxKx )
   at DurtyClothTool.App.App.Main()
```

App Version: **2.5.2.2**
Project targets: **0**
DLC name: **Bomme**
Collection name: ** // **
Project path: **E:\Admiration FiveM\bb Pack Bomme Full\Projets\test\clothproject_sAdd**
Output path: **E:\Admiration FiveM\bb Pack Bomme Full\Projets\test**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment] 2024-02-12 23:24
Duplicate of #174

**Closed as completed by DurtyFree** 2024-02-12 23:24 UTC
