### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by XxIsabel023xX** [DurtyFree/durty-cloth-tool#139] opened 2023-07-22 21:58 UTC
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at q9DXreEXx7wa4Ksa7r9.zFTF67EMAWhaIXhHIyZ.AX9jnbdyEOEHEaFY8WFW(Object , Object )
   at q9DXreEXx7wa4Ksa7r9.zFTF67EMAWhaIXhHIyZ.HDmEPSCWHL(FVDAR4Inbhj2HAlCE09  , String  , String  , String  , String  , ProgressDialog  )
```

App Version: **2.5.1.0**
Items: **4 project items (4C / 0D)**
Project targets: **3**
DLC name: **mattdsi**
Collection name: **mattdsi // **
Project path: **E:\mattdsi\clothproject_mattdsi**
Output path: **E:\mattdsi**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here]`

**Comment by DurtyFree** [comment] 2023-07-26 10:29
Duplicate of #137 thanks for reporting!

**Closed as completed by DurtyFree** 2023-07-26 10:29 UTC
