### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by aronne0pefkkcpoekk** [DurtyFree/durty-cloth-tool#175] opened 2024-02-12 22:49 UTC
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at (Object )
   at uhEU3TfBn6wUbNUvIFQ9.XGEf4oUTHpC(Object , uhEU3TfBn6wUbNUvIFQ9 )
   at NENn0LPd4rMOW2opoyE.kjl4egPNmgwenJbWMw9.HHhPIquiJ1(DateTime  , String  )
   at NENn0LPd4rMOW2opoyE.kjl4egPNmgwenJbWMw9.VflPnjcBqB(String  )
   at HdINi4NRCadndIgU1JG.r8mMtFN5moqtdWZUdGl.uQqodV0fHWxYZYcKF8Dx(Object , Object )
   at HdINi4NRCadndIgU1JG.r8mMtFN5moqtdWZUdGl.uE6NmSKmmS(String  )
   at YbNspLWWP3lMCJORlvZ.daVwBlWBeIytYK1kN9G.e5yWbLXIhk(List`1  )
   at YbNspLWWP3lMCJORlvZ.daVwBlWBeIytYK1kN9G.RBJW3YvPuS(List`1  )
   at YbNspLWWP3lMCJORlvZ.daVwBlWBeIytYK1kN9G.BbKWuBrj9b()
   at g9l8FpoPFumcOZHCsgp.r5ZcyMolxpj5umIcddH.tq8ocCZ2E8(Object  , RoutedEventArgs  )
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.2.2**
Project targets: **0**
DLC name: **Bomme**
Collection name: ** // **
Project path: **E:\Admiration FiveM\bb Pack Bomme Full\Projets\test\clothproject_sAdd**
Output path: **E:\Admiration FiveM\bb Pack Bomme Full\Projets\test**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment] 2024-02-12 23:24
Duplicate of #174

**Closed as completed by DurtyFree** 2024-02-12 23:24 UTC
