### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by Enzo-DC** [DurtyFree/durty-cloth-tool#38] opened 2022-01-17 19:27 UTC
I have the following error:
System.ArgumentException: Caratteri non validi nel percorso.
   in System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
   in System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
   in System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   in System.IO.Path.GetFullPathInternal(String path)
   in System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   in System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   in altClothTool.App.Builders.FivemResourceBuilder.CopyClothTextureToResource(String clothTextureFilePath, Int32 sexNr, String outputFolder, String collectionName, String componentNumerics, String prefix, String ytdPostfix, Char offsetLetter) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\FivemResourceBuilder.cs:riga 60
   in altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:riga 56
   in altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:riga 28

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment] 2022-01-17 19:49
Duplicate of #37

**Closed by DurtyFree** 2022-01-17 19:49 UTC
