### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by KingOutlawFox** [DurtyFree/durty-cloth-tool#234] opened 2024-06-18 02:06 UTC
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at (Object )
   at nOAw9BAetTQEokFr8fN0.KM7A8qvxIal(Object , nOAw9BAetTQEokFr8fN0 )
   at fq158Op1YJDhhy559to.toRunMpe7L6X38ZDHkY.GGgpLfE7N8(DateTime  , String  )
   at fq158Op1YJDhhy559to.toRunMpe7L6X38ZDHkY.eeHpEgO8gk(String  )
   at wa8RnU1XmrVb4nJ2SWI.RwgwMM1Ckd4FTBLSGGi.ISG1DTmBSY(String  )
   at tVWS7UVSsvvnI4Ze2Xb.VLCIQLVst3MXEqbWRQG.a8XVZN3o8j(Exception  , String  )
   at tVWS7UVSsvvnI4Ze2Xb.VLCIQLVst3MXEqbWRQG.K63Vuq19dI(Object  , DispatcherUnhandledExceptionEventArgs  )
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at zR9y8mA8WrDlQ6DrFeTi.KM7A8qvxIal(Object , zR9y8mA8WrDlQ6DrFeTi )
   at DurtyClothTool.App.App.Main()
```

App Version: **2.5.3.0**
Project targets: **0**
DLC name: **OFTV_CivilianV2**
Collection name: ** // **
Project path: **C:\Users\deerd\OneDrive\Desktop\DurtyClothTool.App\clothproject_OFTV_CivilianV2**
Output path: **C:\Users\deerd\OneDrive\Desktop\DurtyClothTool.App**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment] 2024-06-18 08:29
Duplicate of #233

**Closed as completed by DurtyFree** 2024-06-18 08:29 UTC
