### ISSUE TITLE
Insufficient memory to continue the execution of the program.

### ISSUE THREAD

**Issue by MrJaskier** [DurtyFree/durty-cloth-tool#307] opened 2024-09-01 18:03 UTC
I have the following error:
```
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.5**
Project targets: **AltV**
DLC name: **main_pack**
Collection name: ** // **
Project path: **D:\Pulpit\EUP OUTPUT\clothproject_main_pack**
Output path: **D:\Pulpit\EUP OUTPUT**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment] 2024-09-03 15:56
Hi @MrJaskier how much RAM does your PC have and did this occur again since that?

**Comment by MrJaskier** [comment] 2024-09-03 19:19
Hi,
I have 32gb ram. It is the second time when I am working on big clothes
pack.

wt., 3 wrz 2024, 17:56 użytkownik Alexander Schmid ***@***.***>
napisał:

**Comment by DurtyFree** [comment] 2024-09-04 08:54
@MrJaskier is it possible to provide reproduction steps for me + upload and send me the cloth pack that causes this privately? (Via DM `@DurtyFree` on discord)

**Comment by MrJaskier** [comment] 2024-09-04 10:03
Providing pack with 10-15GB size might be difficult.

śr., 4 wrz 2024, 10:55 użytkownik Alexander Schmid ***@***.***>
napisał:

**Comment by MrJaskier** [comment] 2024-09-04 10:04
I will tryb to note what l've done if the issue will appear again.


śr., 4 wrz 2024, 10:55 użytkownik Alexander Schmid ***@***.***>
napisał:

**Comment by DurtyFree** [comment] 2024-09-20 09:13
Until more information provided I'll close this ticket. Feel free to reopen at any time with more details :D

**Closed as completed by DurtyFree** 2024-09-20 09:13 UTC
Labels: bug, more info needed
