### ISSUE TITLE
System.OverflowException: Value was either too large or too small for an unsigned byte.

### ISSUE THREAD

**Issue by Goykz** [DurtyFree/durty-cloth-tool#47] opened 2022-02-23 00:45 UTC
I have the following error:
System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Number.ThrowOverflowException(TypeCode type)
   at System.Convert.ToByte(String value)
   at CodeWalker.GameFiles.XmlMeta.Traverse(XmlNode node, MetaBuilder mb, MetaName type, Boolean isRoot)
   at CodeWalker.GameFiles.XmlMeta.TraverseArrayStructure(XmlNode node, MetaBuilder mb, MetaName type)
   at CodeWalker.GameFiles.XmlMeta.TraverseArray(XmlNode node, MetaBuilder mb, MetaStructureEntryInfo_s arrEntry, Int32 offset, ArrayResults results)
   at CodeWalker.GameFiles.XmlMeta.Traverse(XmlNode node, MetaBuilder mb, MetaName type, Boolean isRoot)
   at CodeWalker.GameFiles.XmlMeta.GetMeta(XmlDocument doc)
   at wwc7vglSfpXiFqSF44W.yZGaX6QZbs(XmlDocument , wwc7vglSfpXiFqSF44W )
   at IFmVaHOg7CQkVLSFdlM.UpWxjpOcyrRKH72CUXF.ymZOh6veAs(String  , List`1  )
   at PuyWUnO19025gUTeNHd.SbPMr8OqDNRUYFS1jxd.jSgOXSV1GE(String  , String  )
   at PuyWUnO19025gUTeNHd.SbPMr8OqDNRUYFS1jxd.kaQDAMjdTf(String  , String  )
   at CQC9bpOE0RVDHRudJiV.yfbLvkOntA8EeyUilnd.I9EOuT1hUQ(qwL8qvnnMfAm2inOFJP  , String  , String  , ProgressDialog  )

App Version: **2.3**
Items: **2200 project items (2200C / 0D)**
Project targets: **2**
Collection name: **go**
Output path: **C:\Users\\Desktop\clothinggo**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**

Cloth files:
[Please provide cloth files (ydd, ytd), cloth project and any other related files here]

**Comment by DurtyFree** [comment] 2022-02-23 08:35
This is a bug I will have to invsetigate further, it is related to some drawable that is too big or something.

Will check on that.

**Comment by soniXx123** [comment] 2022-03-12 16:14
any news about this? how we can find our what file it is?

**Comment by DurtyFree** [comment] 2022-03-13 19:42
> any news about this? how we can find our what file it is?

Haven't had time looking into this yet - for now you can try removing couple of clothes and just try building, until you find the one causing this issue.
Would also be good if that exact one could be send to me then for testing

**Comment by Hex2319** [comment] 2022-03-14 00:24
> 

I took out the largest files i had in my pack, there is nothing over 10 mbs and i am still getting this issue.

**Comment by Hex2319** [comment] 2022-03-14 01:25
I can confirm with other large packs I am making that this error happens when it needs to make the YMT and manifest files

**Comment by DurtyFree** [comment] 2022-03-14 11:05
Please remove cloth files until you find the issue, maybe its just too many clothes or similar

**Comment by Hex2319** [comment] 2022-03-15 18:03
> Please remove cloth files until you find the issue, maybe its just too many clothes or similar

Any update on the fix for this issue?

**Comment by DurtyFree** [comment] 2022-03-15 18:44
> > Please remove cloth files until you find the issue, maybe its just too many clothes or similar
> 
> Any update on the fix for this issue?

Not yet

**Comment by Hex2319** [comment] 2022-03-27 22:42
Any updates on this yet? Waiting for this fix so i can add clothes in

**Comment by Hex2319** [comment] 2022-04-20 20:36
It's been almost 2 months to the day this issue was first reported. Is this issue getting any closer to being fixed?

**Comment by DurtyFree** [comment] 2022-04-21 07:02
> It's been almost 2 months to the day this issue was first reported. Is this issue getting any closer to being fixed?

As many times answered on my discord already; This issue is nothing easy that can be straight up fixed and things work perfectly fine. Because the cause of it is basically either in the amount of clothes or in some specific clothes size of your resource - you should investigate it.

My fix will most likely end up maybe pointing out some specific files to be removed or whatever. Theres no "fix to continue adding more clothes"

**Comment by DurtyFree** [comment] 2022-05-29 01:21
This is "fixed" in the next update.

Actually the reason for this is too huge cloth collections. As the game only can properly stream and sync cloth drawables up to 128 per type, everything above will be kind of random/useless anyway. 
This error occurs because you probably went even more crazy and have hit the actual data type limit for the drawable ids, which is 255. 

In other words; Split your cloth collection and make sure to not go above 128 per drawable type.
![grafik](https://user-images.githubusercontent.com/20757266/170848035-9850da9f-b3b4-42aa-962b-ca94e09c9115.png)
Next update will add this dialog and basically just not allow building before you have fixed your collection by removing clothes & splitting it into a second collection.

**Comment by DurtyFree** [comment] 2023-02-07 20:27
Fixed in v2.5.0, feel free to check it out & download here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.5.0

**Closed by DurtyFree** 2023-02-07 20:27 UTC
Labels: bug, fixed next update, confirmed
