### ISSUE TITLE
Value was either too large or too small for an unsigned byte.

### ISSUE THREAD

**Issue by ThatSake** [DurtyFree/durty-cloth-tool#340] opened 2024-10-07 14:58 UTC
I have the following error:
```
System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Number.ThrowOverflowException(TypeCode type)
   at System.Convert.ToByte(String value)
   at CodeWalker.GameFiles.XmlMeta.Traverse(XmlNode node, MetaBuilder mb, MetaName type, Boolean isRoot)
   at CodeWalker.GameFiles.XmlMeta.Traverse(XmlNode node, MetaBuilder mb, MetaName type, Boolean isRoot)
   at CodeWalker.GameFiles.XmlMeta.GetMeta(XmlDocument doc)
   at d7caoZhsYCXGUjnw3Hq0.c9ysrR0Ya75(XmlDocument , d7caoZhsYCXGUjnw3Hq0 )
   at LTqUt8bPnBgtOfWwLLw.bvsm5UbK3u46LXBRHfu.x8fdIUcHdV(String  , List`1  )
   at ABvQdfbp3c5hFQQqm0P.x8l3C9b67o0dNOWgPmO.OnwbHWmOkC(String  , String  , String  , String  )
   at ABvQdfbp3c5hFQQqm0P.x8l3C9b67o0dNOWgPmO.HassPEnkkqi(String  , String  , String  , String  )
   at TDr26cRo2tyo1jw3ZAB.eiC2AdRHs2oynkaHMvP.LrLYZ0h2YAqhyPOZBEMv(Object , Object , Object , Object , Object )
   at TDr26cRo2tyo1jw3ZAB.eiC2AdRHs2oynkaHMvP.OdoRYYa6CZ(TargetResourceType  , String  , String  , String  , String  , ProgressDialog  )
```

App Version: **3.0.0.8**
Items: **1510 project items (1510C / 0D)**
Project targets: **FiveM**
DLC name: **sakes_flexxpk**
Collection name: **sakes_flexxpk // **
Project path: **F:\SAKES CLOSET\GTA V\OPEN PROJECTS\CLOTHING PACKS\MALE\Flexx Pack\OUTPUT\clothproject_sakes_flexxpk**
Output path: **F:\SAKES CLOSET\GTA V\OPEN PROJECTS\CLOTHING PACKS\MALE\Flexx Pack\OUTPUT**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **True**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment] 2024-10-13 16:41
Duplicate of #329

**Closed as completed by DurtyFree** 2024-10-13 16:41 UTC
