### ISSUE TITLE
illegal position! when reading YDD file

### ISSUE THREAD

**Issue by cokeboogies** [DurtyFree/durty-cloth-tool#170] opened 2024-02-09 22:33 UTC
I have the following error:
```
System.Exception: illegal position!
   at CodeWalker.GameFiles.ResourceDataReader.ReadFromStream(Int32 count, Boolean ignoreEndianess)
   at CodeWalker.GameFiles.DataReader.ReadBytes(Int32 count)
   at CodeWalker.GameFiles.ResourceDataReader.ReadStruct[T]()
   at CodeWalker.GameFiles.ResourceDataReader.ReadStructAt[T](Int64 position)
   at CodeWalker.GameFiles.DrawableModelsBlock.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlockAt[T](UInt64 position, Object[] parameters)
   at CodeWalker.GameFiles.DrawableBase.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.Drawable.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlockAt[T](UInt64 position, Object[] parameters)
   at CodeWalker.GameFiles.ResourcePointerArray64`1.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlockAt[T](UInt64 position, Object[] parameters)
   at CodeWalker.GameFiles.DrawableDictionary.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.YddFile.Load(Byte[] data, RpfFileEntry entry)
   at CodeWalker.GameFiles.RpfFile.LoadResourceFile[T](T file, Byte[] data, UInt32 ver)
   at CodeWalker.GameFiles.YddFile.Load(Byte[] data)
   at Xderrsf1nTUgFW6nEAQi.XGEf4oUTHpC(Object , Byte[] , Xderrsf1nTUgFW6nEAQi )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.c5U0gMfkJ9(Int32  , String  , String  )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.brtyF5bHFI(Boolean  )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.ujZytpeOy5()
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.lpWyORQZJ0()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

App Version: **2.5.2.2**
Project targets: **2**
DLC name: **Advtut**
Collection name: **frp // **
Project path: **C:\Users\rance\Desktop\clothproject_Advtut**
Output path: **C:\Users\rance\Desktop**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by cokeboogies** [comment] 2024-02-09 22:53
The p_head files do not show up in durty cloth or openiv

**Comment by DurtyFree** [comment] 2024-02-11 13:02
Hi @cokeboogies pls upload the related files and explain how to reproduce this error

**Comment by DurtyFree** [comment] 2024-03-18 12:53
Caused by most likely badly made or corrupted cloth model. Case is handled next update

Related to #197

**Comment by DurtyFree** [comment] 2024-03-20 15:13
Fixed in https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.5.3.0

**Closed as completed by DurtyFree** 2024-03-20 15:13 UTC
Labels: bug, next update
