### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by Hex2319** [DurtyFree/durty-cloth-tool#49] opened 2022-03-03 05:05 UTC
I have the following error:
System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Number.ThrowOverflowException(TypeCode type)
   at System.Convert.ToByte(String value)
   at CodeWalker.GameFiles.XmlMeta.Traverse(XmlNode node, MetaBuilder mb, MetaName type, Boolean isRoot)
   at CodeWalker.GameFiles.XmlMeta.TraverseArrayStructure(XmlNode node, MetaBuilder mb, MetaName type)
   at CodeWalker.GameFiles.XmlMeta.TraverseArray(XmlNode node, MetaBuilder mb, MetaStructureEntryInfo_s arrEntry, Int32 offset, ArrayResults results)
   at CodeWalker.GameFiles.XmlMeta.Traverse(XmlNode node, MetaBuilder mb, MetaName type, Boolean isRoot)
   at CodeWalker.GameFiles.XmlMeta.GetMeta(XmlDocument doc)
   at wwc7vglSfpXiFqSF44W.yZGaX6QZbs(XmlDocument , wwc7vglSfpXiFqSF44W )
   at IFmVaHOg7CQkVLSFdlM.UpWxjpOcyrRKH72CUXF.ymZOh6veAs(String  , List`1  )
   at PuyWUnO19025gUTeNHd.SbPMr8OqDNRUYFS1jxd.jSgOXSV1GE(String  , String  )
   at PuyWUnO19025gUTeNHd.SbPMr8OqDNRUYFS1jxd.kaQDAMjdTf(String  , String  )
   at CQC9bpOE0RVDHRudJiV.yfbLvkOntA8EeyUilnd.I9EOuT1hUQ(qwL8qvnnMfAm2inOFJP  , String  , String  , ProgressDialog  )

App Version: **2.3**
Items: **2340 project items (2340C / 0D)**
Project targets: **2**
Collection name: **6thsenseclothes**
Output path: **C:\Users\cheim\Documents\GitHub\6thSenseRP\resources\[addons]\[clothes]\6thClothesNew**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**

Cloth files:
[Please provide cloth files (ydd, ytd), cloth project and any other related files here]

**Comment by DurtyFree** [comment] 2022-03-03 09:10
Duplicate of #47

**Closed by DurtyFree** 2022-03-03 09:10 UTC
