### ISSUE TITLE
Stream length must be non-negative and less than 2^31 - 1 - origin. (Parameter 'value')

### ISSUE THREAD

**Issue by notDAURYS** [DurtyFree/durty-cloth-tool#178] opened 2024-02-18 04:33 UTC
I have the following error:
```
System.ArgumentOutOfRangeException: Stream length must be non-negative and less than 2^31 - 1 - origin. (Parameter 'value')
   at System.IO.MemoryStream.set_Position(Int64 value)
   at CodeWalker.GameFiles.ResourceDataReader.ReadFromStream(Int32 count, Boolean ignoreEndianess)
   at CodeWalker.GameFiles.DataReader.ReadUInt32()
   at CodeWalker.GameFiles.Joints.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlockAt[T](UInt64 position, Object[] parameters)
   at CodeWalker.GameFiles.DrawableBase.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.Drawable.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlockAt[T](UInt64 position, Object[] parameters)
   at CodeWalker.GameFiles.ResourcePointerArray64`1.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlockAt[T](UInt64 position, Object[] parameters)
   at CodeWalker.GameFiles.DrawableDictionary.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.YddFile.Load(Byte[] data, RpfFileEntry entry)
   at CodeWalker.GameFiles.RpfFile.LoadResourceFile[T](T file, Byte[] data, UInt32 ver)
   at CodeWalker.GameFiles.YddFile.Load(Byte[] data)
   at Xderrsf1nTUgFW6nEAQi.XGEf4oUTHpC(Object , Byte[] , Xderrsf1nTUgFW6nEAQi )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.c5U0gMfkJ9(Int32  , String  , String  )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.brtyF5bHFI(Boolean  )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.ujZytpeOy5()
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.rrdys44fFG(ClothData  , ClothTextureData  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.PreviewAppearanceItemCommand.Execute(Object  )
   at g9l8FpoPFumcOZHCsgp.r5ZcyMolxpj5umIcddH.SlGgJWyC1GY48gsJvBYW(Object , Object )
   at g9l8FpoPFumcOZHCsgp.r5ZcyMolxpj5umIcddH.HGyoT2opnn(Object  , MouseButtonEventArgs  )
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Control.OnMouseDoubleClick(MouseButtonEventArgs e)
   at System.Windows.Controls.Control.HandleDoubleClick(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.2.2**
Project targets: **0**
DLC name: **STW**
Collection name: ** // **
Project path: **C:\Users\magua\Desktop\DurtyClothTool\STW\clothproject_STW**
Output path: **C:\Users\magua\Desktop\DurtyClothTool\STW**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment] 2024-03-18 12:52
Caused by most likely badly made or corrupted cloth model. Case is handled next update

Related to #197

**Comment by DurtyFree** [comment] 2024-03-20 15:13
Fixed in https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.5.3.0

**Closed as completed by DurtyFree** 2024-03-20 15:13 UTC
Labels: bug, next update
