### ISSUE TITLE
illegal position!

### ISSUE THREAD

**Issue by cokeboogies** [DurtyFree/durty-cloth-tool#171] opened 2024-02-09 22:38 UTC
I have the following error:
```
System.Exception: illegal position!
   at CodeWalker.GameFiles.ResourceDataReader.ReadFromStream(Int32 count, Boolean ignoreEndianess)
   at CodeWalker.GameFiles.DataReader.ReadBytes(Int32 count)
   at CodeWalker.GameFiles.ResourceDataReader.ReadStruct[T]()
   at CodeWalker.GameFiles.ResourceDataReader.ReadStructAt[T](Int64 position)
   at CodeWalker.GameFiles.DrawableModelsBlock.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlockAt[T](UInt64 position, Object[] parameters)
   at CodeWalker.GameFiles.DrawableBase.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.Drawable.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlockAt[T](UInt64 position, Object[] parameters)
   at CodeWalker.GameFiles.ResourcePointerArray64`1.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlockAt[T](UInt64 position, Object[] parameters)
   at CodeWalker.GameFiles.DrawableDictionary.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.YddFile.Load(Byte[] data, RpfFileEntry entry)
   at CodeWalker.GameFiles.RpfFile.LoadResourceFile[T](T file, Byte[] data, UInt32 ver)
   at CodeWalker.GameFiles.YddFile.Load(Byte[] data)
   at Xderrsf1nTUgFW6nEAQi.XGEf4oUTHpC(Object , Byte[] , Xderrsf1nTUgFW6nEAQi )
   at y1P1rDIZm76ClVrwAgE.M27FR5IhGRYlKcV7vIh.Ri6IxjP95G(String  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.OptimizeAppearanceItemCommand.Execute(Object  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.2.2**
Project targets: **2**
DLC name: **Advtut**
Collection name: **frp // **
Project path: **C:\Users\rance\Desktop\clothproject_Advtut**
Output path: **C:\Users\rance\Desktop**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment] 2024-02-11 13:02
Duplicate of #170

**Closed as completed by DurtyFree** 2024-02-11 13:02 UTC
