### ISSUE TITLE
Value was either too large or too small for an unsigned byte.

### ISSUE THREAD

**Issue by YamacEfendi** [DurtyFree/durty-cloth-tool#145] opened 2023-09-28 11:50 UTC
I have the following error:
```
System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Number.ThrowOverflowException(TypeCode type)
   at System.Convert.ToByte(String value)
   at CodeWalker.GameFiles.XmlMeta.Traverse(XmlNode node, MetaBuilder mb, MetaName type, Boolean isRoot)
   at CodeWalker.GameFiles.XmlMeta.Traverse(XmlNode node, MetaBuilder mb, MetaName type, Boolean isRoot)
   at CodeWalker.GameFiles.XmlMeta.GetMeta(XmlDocument doc)
   at o63soGIEtrtpdOmsuh3r.lEoIn5rAbL6(XmlDocument , o63soGIEtrtpdOmsuh3r )
   at FmlmIc2zppAWhOnt3yR.ASIhkQ2q0sMf82xSv1G.bbunwqlpgU(String  , List`1  )
   at grJKFL2GnvT1rDI5VwM.okgP8l2daTkPqFFhy3C.yMJ2HWLrrP(String  , String  , String  , String  )
   at grJKFL2GnvT1rDI5VwM.okgP8l2daTkPqFFhy3C.rZ0IVlpInMx(String  , String  , String  , String  )
   at OeRQwLO9rZ0fScEynnH.U5BfsfOGiXjfWsyMJeA.iJoOhZKliW(Jd3HLntApaCFk1ouB1a  , String  , String  , String  , String  , ProgressDialog  )
```

App Version: **2.5.1.1**
Items: **5167 project items (5167C / 0D)**
Project targets: **2**
DLC name: **2023Clothe**
Collection name: **kayzm // **
Project path: **E:\2023\clothproject_2023Clothe**
Output path: **E:\2023**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here]`

**Comment by DurtyFree** [comment] 2023-09-28 18:11
Thank you for reporting

Duplicate of #143

**Closed as completed by DurtyFree** 2023-09-28 18:11 UTC
