### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Lilianawiwi** [DurtyFree/durty-cloth-tool#187] opened 2024-02-27 04:08 UTC
I have the following error:
```
System.IO.IOException: A sintaxe do nome do ficheiro, do nome do diretório ou da etiqueta do volume é incorreta. : 'C:\Users\wiwid\Desktop\Texturas\29\Cardo" Modworks.png'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Create(String path)
   at SixLabors.ImageSharp.IO.LocalFileSystem.Create(String path)
   at SixLabors.ImageSharp.ImageExtensions.Save(Image source, String path, IImageEncoder encoder)
   at SixLabors.ImageSharp.ImageExtensions.SaveAsPng(Image source, String path, PngEncoder encoder)
   at SixLabors.ImageSharp.ImageExtensions.SaveAsPng(Image source, String path)
   at dwDbKXfWz3xT4NAXpGtV.XGEf4oUTHpC(Image , String , dwDbKXfWz3xT4NAXpGtV )
   at nNlyRvvRUZU77Hr5dDM.yw4cRlv5Y57JTHHAkyC.nVOvDFdJKc(String  , TextureDictionary  )
   at nNlyRvvRUZU77Hr5dDM.yw4cRlv5Y57JTHHAkyC.b1Pvcr92rF(String  , String  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.jIccb8nc1e(List`1  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.Execute(Object  )
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.2.2**
Project targets: **0**
DLC name: **3qpixel**
Collection name: ** // **
Project path: **C:\Users\wiwid\Desktop\3Q Pixel Pack Roupas\clothproject_3qpixel**
Output path: **C:\Users\wiwid\Desktop\3Q Pixel Pack Roupas**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment] 2024-02-27 10:20
Duplicate of #169

**Closed as completed by DurtyFree** 2024-02-27 10:20 UTC
