### ISSUE TITLE
App crashes / Out of memory with 810++ clothes

### ISSUE THREAD

**Issue by bigsmileling** [DurtyFree/durty-cloth-tool#4] opened 2021-02-08 19:14 UTC
Building SP file.

I have the following error:
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at RageLib.Data.PartialStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at RageLib.GTA5.ArchiveWrappers.RageArchiveResourceFileWrapper7.Import(Stream stream)
   at RageLib.GTA5.ArchiveWrappers.RageArchiveResourceFileWrapper7.Import(String fileName)
   at altClothTool.App.Builders.SingleplayerResourceBuilder.BuildResource(String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\SingleplayerResourceBuilder.cs:line 237
   at altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:line 23

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here] <- I can't because I've tried with 810 clothes.

https://i.imgur.com/flOPAeT.png

**Comment by DurtyFree** [comment] 2021-02-09 15:53
Seems like the application run out of memory, I am not sure if I should try to add support for 810 clothes. 

Maybe rather try splitting up your project into multiple?

**Comment by bigsmileling** [comment] 2021-02-09 17:07
The only way to be able to use a single player .RPF is creating it from 0 and using the YTM and the .meta file that are created using ALT: V build, about the memory, it's not much problem for me if it consumes a little more.

My idea is to use a single file for everything, although I don't know if it is possible to split it into several DLC files, I mean, one .rpf for jbib, another .rpf for lowr, another .rpf for accs, etc, I don't know if GTA allows this.

**Comment by DurtyFree** [comment] 2021-02-09 20:20
I see, I will consider this as a feature request. But it will be hard to improve / fix as I cannot reproduce it (I dont have a project with that many clothes)

**Comment by DurtyFree** [comment] 2021-09-20 16:27
This should be fixed with the next version, thx

**Closed by DurtyFree** 2021-09-20 16:27 UTC
Labels: enhancement, confirmed

**Comment by DurtyFree** [comment] 2021-09-28 20:12
Latest version that should fix this is now available here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.1
