### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by jac50616** [DurtyFree/durty-cloth-tool#213] opened 2024-04-11 23:49 UTC
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at (Object , Single )
   at iYismEA4RAKQHjNm6tl3.KM7A8qvxIal(Object , Single , iYismEA4RAKQHjNm6tl3 )
   at AELwuEV9suArmhdjLB0.w6l0FPV3Xx9CIR5fxqm.TLBqke8KuR(Object  , EventArgs  )
   at System.Windows.Forms.TrackBar.OnScroll(EventArgs e)
   at System.Windows.Forms.TrackBar.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

App Version: **2.5.3.0**
Project targets: **0**
DLC name: **a**
Collection name: ** // **
Project path: **C:\Users\PC\Downloads\uniforme arabe\clothproject_a**
Output path: **C:\Users\PC\Downloads\uniforme arabe**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment] 2024-04-15 21:09
Duplicate of #209

**Closed as completed by DurtyFree** 2024-04-15 21:09 UTC
