### ISSUE TITLE
Stream length must be non-negative and less than 2^31 - 1 - origin. (Parameter 'value')

### ISSUE THREAD

**Issue by Packked** [DurtyFree/durty-cloth-tool#198] opened 2024-03-09 20:30 UTC
I have the following error:
```
System.ArgumentOutOfRangeException: Stream length must be non-negative and less than 2^31 - 1 - origin. (Parameter 'value')
   at System.IO.MemoryStream.set_Position(Int64 value)
   at CodeWalker.GameFiles.ResourceDataReader.ReadFromStream(Int32 count, Boolean ignoreEndianess)
   at CodeWalker.GameFiles.DataReader.ReadUInt32()
   at CodeWalker.GameFiles.Joints.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlockAt[T](UInt64 position, Object[] parameters)
   at CodeWalker.GameFiles.DrawableBase.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.Drawable.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlockAt[T](UInt64 position, Object[] parameters)
   at CodeWalker.GameFiles.ResourcePointerArray64`1.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlockAt[T](UInt64 position, Object[] parameters)
   at CodeWalker.GameFiles.DrawableDictionary.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.YddFile.Load(Byte[] data, RpfFileEntry entry)
   at CodeWalker.GameFiles.RpfFile.LoadResourceFile[T](T file, Byte[] data, UInt32 ver)
   at CodeWalker.GameFiles.YddFile.Load(Byte[] data)
   at Xderrsf1nTUgFW6nEAQi.XGEf4oUTHpC(Object , Byte[] , Xderrsf1nTUgFW6nEAQi )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.c5U0gMfkJ9(Int32  , String  , String  )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.brtyF5bHFI(Boolean  )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.ujZytpeOy5()
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.lpWyORQZJ0()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

App Version: **2.5.2.2**
Project targets: **0**
DLC name: **xsa_chain**
Collection name: ** // **
Project path: **C:\Users\alext\OneDrive\Desktop\yh\clothproject_xsa_chain**
Output path: **C:\Users\alext\OneDrive\Desktop\yh**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment] 2024-03-09 21:00
Duplicate of #178

**Closed as completed by DurtyFree** 2024-03-09 21:00 UTC
