### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by keiraskyler** [DurtyFree/durty-cloth-tool#201] opened 2024-03-10 21:52 UTC
![DurtyClothTool App_2oxneTNQBw](https://github.com/DurtyFree/durty-cloth-tool/assets/56744506/3fca9bd4-cd9a-4d13-945a-42f7e1677204)
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at g9l8FpoPFumcOZHCsgp.r5ZcyMolxpj5umIcddH.YGVkqlyC7CRPG4lVq4Th(Object )
   at g9l8FpoPFumcOZHCsgp.r5ZcyMolxpj5umIcddH.wf1hCOIFXT(Object  , KeyboardFocusChangedEventArgs  )
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(Tuple`2 postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.PossiblyDeactivate(IntPtr hwndFocus)
   at System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.2.2**
Project targets: **0**
DLC name: **CSGClothPackFemale**
Collection name: ** // **
Project path: **C:\Users\keira\Desktop\DurtyClothTool.App\clothproject_CSGClothPackFemale**
Output path: **C:\Users\keira\Desktop\DurtyClothTool.App**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment] 2024-03-11 14:43
Duplicate of #193

**Closed as completed by DurtyFree** 2024-03-11 14:43 UTC
