### ISSUE TITLE
Name cannot begin with the '0' character, hexadecimal value 0x30. Line 449, position 58.

### ISSUE THREAD

**Issue by Airidas-Fix** [DurtyFree/durty-cloth-tool#177] opened 2024-02-14 02:18 UTC
I have the following error:
```
System.Xml.XmlException: Name cannot begin with the '0' character, hexadecimal value 0x30. Line 449, position 58.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at CodeWalker.GameFiles.RpfManager.GetFileXml(String path)
   at CodeWalker.World.TimecycleMods.Init(GameFileCache gameFileCache, Action`1 updateStatus)
   at CodeWalker.World.Weather.Init(GameFileCache gameFileCache, Action`1 updateStatus, Timecycle timecycle)
   at iDDYYIfHhOWLZ7j9YHhn.XGEf4oUTHpC(Object , GameFileCache , Action`1 , Timecycle , iDDYYIfHhOWLZ7j9YHhn )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.SsvyW6BE2C()
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.o2qyQ89SFy()
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Thread.StartCallback()
```

App Version: **2.5.2.2**
Project targets: **0**
DLC name: **apranga**
Collection name: ** // **
Project path: **C:\Users\Air\Desktop\DurtyToolV\Output\clothproject_apranga**
Output path: **C:\Users\Air\Desktop\DurtyToolV\Output**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment] 2024-02-28 16:12
Duplicate of #183

**Closed as completed by DurtyFree** 2024-02-28 16:12 UTC
Labels: bug
