### ISSUE TITLE
The archive entry was compressed using an unsupported compression method.

### ISSUE THREAD

**Issue by 538179** [DurtyFree/durty-cloth-tool#167] opened 2024-02-08 14:35 UTC
![error](https://github.com/DurtyFree/durty-cloth-tool/assets/159455472/73a08c46-1048-46cd-a46b-f1b4c3b7367a)

I have the following error:
```
System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.CopyToStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
   at System.IO.Compression.DeflateStream.CopyTo(Stream destination, Int32 bufferSize)
   at CodeWalker.GameFiles.ResourceBuilder.Decompress(Byte[] data)
   at CodeWalker.GameFiles.RpfFile.LoadResourceFile[T](T file, Byte[] data, UInt32 ver)
   at CodeWalker.GameFiles.YddFile.Load(Byte[] data)
   at Xderrsf1nTUgFW6nEAQi.XGEf4oUTHpC(Object , Byte[] , Xderrsf1nTUgFW6nEAQi )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.c5U0gMfkJ9(Int32  , String  , String  )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.brtyF5bHFI(Boolean  )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.ujZytpeOy5()
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.rrdys44fFG(ClothData  , ClothTextureData  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.PreviewAppearanceItemCommand.Execute(Object  )
   at g9l8FpoPFumcOZHCsgp.r5ZcyMolxpj5umIcddH.SlGgJWyC1GY48gsJvBYW(Object , Object )
   at g9l8FpoPFumcOZHCsgp.r5ZcyMolxpj5umIcddH.uwaoHmvo9v(Object  , MouseButtonEventArgs  )
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Control.HandleDoubleClick(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.2.2**
Project targets: **0**
DLC name: **updated**
Collection name: ** // **
Project path: **E:\clothproject_updated**
Output path: **E:\**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment] 2024-02-11 13:04
Hi @538179 pls upload related files and reproduction steps for this error

**Comment by DurtyFree** [comment] 2024-03-18 12:53
Caused by most likely badly made or corrupted cloth model. Case is handled next update

Related to #197

**Comment by DurtyFree** [comment] 2024-03-20 15:14
Fixed in https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.5.3.0

**Closed as completed by DurtyFree** 2024-03-20 15:14 UTC
Labels: bug, next update
